### ISSUE TITLE
NameError: name 'in_file' is not defined

### ISSUE THREAD

**Issue by david-roquis** [JingfangSI/SnpCountCU#1]
Hello! 

I am trying to use your tool to count the number of unique SNPs for each of my populations, but I get an error while trying to run the tool. I am using the following command:

python3 SnpCountCU.py -v multiSNP.Poudel.Phased.Final.vcf.gz -l samples_list.txt --out test.count.txt -r Regions.txt

and get the following stdout and stderr
[2022-10-26 11:09:03] INFO: Start SnpCount. Total populations : 7.
[2022-10-26 11:09:03] INFO: Start SnpCount. Total chromosome  : 176.
[2022-10-26 11:09:03] INFO: ========================================================
[2022-10-26 11:09:03] INFO: PID:18118  MEM:41.97MB
[2022-10-26 11:09:03] INFO: Chromosome PGTG_00002T0
[2022-10-26 11:09:03] INFO: ========================================================
[2022-10-26 11:09:03] INFO: Start count population: Delley
[2022-10-26 11:09:03] INFO: Start count population: Cadenazzo_Pure
[2022-10-26 11:09:03] INFO: Start count population: Zurich
[2022-10-26 11:09:03] INFO: Start count population: Changins
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/david/miniconda3/envs/numpy/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/david/miniconda3/envs/numpy/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/david/Documents/Bioinformatique/Tools/SnpCountCU/SnpCountCU.py", line 29, in wrapper
    r = func(*args, **kwargs)
  File "/Users/david/Documents/Bioinformatique/Tools/SnpCountCU/SnpCountCU.py", line 102, in vcf_io
    vcf = VCF(in_file)
NameError: name 'in_file' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/david/Documents/Bioinformatique/Tools/SnpCountCU/SnpCountCU.py", line 249, in <module>
    final_run(in_file, chrom, list_pop, dict_id_pop, args.common_pop, args.out)
  File "/Users/david/Documents/Bioinformatique/Tools/SnpCountCU/SnpCountCU.py", line 167, in final_run
    count_out = use_pool(vcf_io, runlist_vcf_io, num_threads)
  File "/Users/david/Documents/Bioinformatique/Tools/SnpCountCU/SnpCountCU.py", line 154, in use_pool
    out = pool.starmap(func, args_list)
  File "/Users/david/miniconda3/envs/numpy/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Users/david/miniconda3/envs/numpy/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
NameError: name 'in_file' is not defined

The file I use is a multi VCF where samples are named "barcode01", "barcode02" etc. and my sample list file looks as such:
Delley	barcode01
Begnins	barcode02
Cadenazzo_Pure	barcode03
Cossonay	barcode04
Zurich	barcode05
Cadenazzo_Mix	barcode06
Changins	barcode09

My region file is a list of all the contigs on which I did SNP calling (176 contigs of +/- 2kb)

I am running the tool in a Conda virtual environment with Python 3, Numpy, Libgfortran3, csutil and cyvcf2 installed
Is there anything I am doing wrong, and do you have any idea how I could solve this issue? Thank you!

**Comment by JingfangSI** [comment]
Hi, 

Thanks for using this script. 
You can try changing "def vcf_io(vcf, chrom, pop, dict_id_pop):" to "def vcf_io(in_file, chrom, pop, dict_id_pop):" on line 100.

Hope this helps you.

**Comment by david-roquis** [comment]
Hello!

It works with your fix. Thank you!
